force-app/main/default/objects/Marketing_Experience__c/Marketing_Experience__c.object-meta.xml
<CustomObject>
    <label>Marketing Experience</label>
    <nameField>
        <label>Marketing Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Experience__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Journey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarketingExperienceController.cls
public with sharing class MarketingExperienceController {
    
    @AuraEnabled(cacheable=true)
    public static List<Marketing_Experience__c> returnAllMarketingExperiences(){
        try {
            system.debug('Are any records returned');
            system.debug([select Name, Source__c, Type__c, createddate from Marketing_Experience__c]);
            return [select Name, Source__c, Type__c, CreatedDate from Marketing_Experience__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}